---
title: "lumpfish feed trial data"
author: "Demitri"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## lumpfish data

I wanted to generate an spreadsheet that has all the lumpfish data

### Read Excel 

initial sheet generated by demitri when Mark and Demitri allocated, pit tagged, and weighed fish. 2nd sheet generated by Mike on 12/6 when we reweighed lumpfish

```{r message = F}
library(tidyverse)
library(readxl)
init <- read_excel("lumpfish_11-22-21_final.xlsx", .name_repair = "universal")
second <- read_excel("2nd_measurement12_6_21.xlsx", .name_repair = "universal")
```

### combine and tidy up 

```{r message = F, warning=F}
joined <- init%>%
  full_join(second, by="Tag.Code", suffix = c(".11.22", ".12.6"))%>%
  select(-num_range("...",7:12))%>%
  rename(comments = ...6)%>%
  mutate_at("Weight.11.22", as.double)%>%
  mutate(weight.change= Weight.12.6 - Weight.11.22)%>%
  mutate(perc.weight.change = weight.change/Weight.11.22*100)

```
### Make table

```{r}
knitr::kable(joined)
```
### histogram

```{r}
x <- joined$Weight.11.22
x <- x[!is.na(x)]
hist(x, breaks=40,
     main = "measurments from 11/22",xlab = "weight in grams")

```
```{r}
y <- joined$Weight.12.6
y <- y[!is.na(y)]
hist(y, breaks=50,
     main = "measurments from 12/6", xlab = "weight in grams")
```

